# Generated by Django 4.1.2 on 2022-11-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='month',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
