# Generated by Django 4.1.2 on 2022-11-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_account_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='pf',
            new_name='af',
        ),
    ]
