# Generated by Django 4.1.2 on 2022-11-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_rename_pf_account_af'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('City', models.CharField(max_length=20)),
                ('Roll', models.IntegerField()),
            ],
            options={
                'db_table': 'student_details',
            },
        ),
    ]
