# Generated by Django 4.1.2 on 2022-11-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='account',
            table='Account',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
    ]
